import Content from '../Сontent/Content';

export default function Header() {
  return (
    <Content>
      <header>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </header>
    </Content>
  );
}
